apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.3.199
    path: /export/nfs/nextcloud/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.3.199
    path: /export/nfs/nextcloud/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: nginx-container
    image: lscr.io/linuxserver/nextcloud:latest
    volumeMounts:
      - mountPath: /config
        name: nextcloud-config
      - mountPath: /data
        name: nextcloud-data
  volumes:
    - name: nextcloud-config
      persistentVolumeClaim:
        claimName: nextcloud-config
    - name: nextcloud-data
      persistentVolumeClaim:
        claimName: nextcloud-data