apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd-client"
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ssd-client
  nfs:
    server: 192.168.3.199
    path: /export/nfs/nextcloud