apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud2
spec:
  serviceName: nextcloud2
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud2
  template:
    metadata:
      labels:
        app: nextcloud2
    spec:
      containers:
      - name: nextcloud
        image: nextcloud
        volumeMounts:
        - name: nextcloud2
          mountPath: /var/www/html/
        ports:
         - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: nextcloud2
    spec:
      storageClassName: ssd-client
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi